//
//  NativeOrtApiStruct.swift
//  VetarAI — Local-first multi-agent orchestration application
//  Copyright (C) 2026 zero11924065-dev
//
//  This file is part of VetarAI.
//
//  VetarAI is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  VetarAI is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with VetarAI. If not, see <https://www.gnu.org/licenses/>.
//

//  ⚠️ 本文件由 ABI 解析机械生成（字段顺序 = 官方头文件逐字顺序），请勿手改字段序。
//
//  出处：onnxruntime v1.29.0 官方头文件 include/onnxruntime/core/session/
//  onnxruntime_c_api.h（ORT_API_VERSION=29，jsdelivr 镜像取得——本机 venv/dist
//  均未随包携带该头文件，GitHub 直连不可达）。struct OrtApi 共 425 个函数指针
//  字段；全部字段均为指针宽度（8 字节），本结构按声明序 1:1 镜像：
//    · 用到的 22 个字段给精确 @convention(c) 类型（编译期防呆）；
//    · 其余字段 UnsafeMutableRawPointer? 占位（保布局，永不调用）。
//  关键索引锚点（解析复核过）：CreateStatus=0 / GetErrorCode=1 / GetErrorMessage=2 /
//  CreateEnv=3 / CreateSession=7 / Run=9 / CreateSessionOptions=10 /
//  SetSessionGraphOptimizationLevel=23 / SetIntraOpNumThreads=24 /
//  CreateTensorWithDataAsOrtValue=49 / GetTensorMutableData=51 / GetDimensionsCount=61 /
//  GetDimensions=62 / GetTensorTypeAndShape=65 / CreateCpuMemoryInfo=69 /
//  ReleaseEnv=92 / ReleaseStatus=93 / ReleaseMemoryInfo=94 / ReleaseSession=95 /
//  ReleaseValue=96 / ReleaseTensorTypeAndShapeInfo=99 / ReleaseSessionOptions=100。
//  尺寸断言在 NativeOnnxRuntimeTests（MemoryLayout == 425*8）。
//

import Foundation

/// OrtApiBase（onnxruntime_c_api.h L937-946；OrtGetApiBase 的返回结构）。
public struct NativeOrtApiBase {
    /// const OrtApi* GetApi(uint32_t version)
    /// （返回 UnsafeRawPointer——@convention(c) 不能返回 Swift struct 指针；
    /// 调用方 assumingMemoryBound(to: NativeOrtApi.self)）
    public let getApi: @convention(c) (UInt32) -> UnsafeRawPointer?
    /// const char* GetVersionString(void)
    public let getVersionString: @convention(c) () -> UnsafePointer<CChar>?
}

/// struct OrtApi v29（425 字段 ABI 镜像；经 dylib 内静态指针只读访问，不拷贝）。
public struct NativeOrtApi {

    /// idx 0: OrtApi::CreateStatus（未用，占位保布局）
    public var createStatus: UnsafeMutableRawPointer?
    /// idx 1: OrtApi::GetErrorCode（未用，占位保布局）
    public var getErrorCode: UnsafeMutableRawPointer?
    /// idx 2: OrtApi::GetErrorMessage
    public var getErrorMessage: (@convention(c) (UnsafeRawPointer?) -> UnsafePointer<CChar>?)?
    /// idx 3: OrtApi::CreateEnv
    public var createEnv: (@convention(c) (Int32, UnsafePointer<CChar>?, UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 4: OrtApi::CreateEnvWithCustomLogger（未用，占位保布局）
    public var createEnvWithCustomLogger: UnsafeMutableRawPointer?
    /// idx 5: OrtApi::EnableTelemetryEvents（未用，占位保布局）
    public var enableTelemetryEvents: UnsafeMutableRawPointer?
    /// idx 6: OrtApi::DisableTelemetryEvents（未用，占位保布局）
    public var disableTelemetryEvents: UnsafeMutableRawPointer?
    /// idx 7: OrtApi::CreateSession
    public var createSession: (@convention(c) (UnsafeRawPointer?, UnsafePointer<CChar>?, UnsafeRawPointer?, UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 8: OrtApi::CreateSessionFromArray（未用，占位保布局）
    public var createSessionFromArray: UnsafeMutableRawPointer?
    /// idx 9: OrtApi::Run
    public var run: (@convention(c) (UnsafeRawPointer?, UnsafeRawPointer?, UnsafePointer<UnsafePointer<CChar>?>?, UnsafePointer<UnsafeMutableRawPointer?>?, Int, UnsafePointer<UnsafePointer<CChar>?>?, Int, UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 10: OrtApi::CreateSessionOptions
    public var createSessionOptions: (@convention(c) (UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 11: OrtApi::SetOptimizedModelFilePath（未用，占位保布局）
    public var setOptimizedModelFilePath: UnsafeMutableRawPointer?
    /// idx 12: OrtApi::CloneSessionOptions（未用，占位保布局）
    public var cloneSessionOptions: UnsafeMutableRawPointer?
    /// idx 13: OrtApi::SetSessionExecutionMode（未用，占位保布局）
    public var setSessionExecutionMode: UnsafeMutableRawPointer?
    /// idx 14: OrtApi::EnableProfiling（未用，占位保布局）
    public var enableProfiling: UnsafeMutableRawPointer?
    /// idx 15: OrtApi::DisableProfiling（未用，占位保布局）
    public var disableProfiling: UnsafeMutableRawPointer?
    /// idx 16: OrtApi::EnableMemPattern（未用，占位保布局）
    public var enableMemPattern: UnsafeMutableRawPointer?
    /// idx 17: OrtApi::DisableMemPattern（未用，占位保布局）
    public var disableMemPattern: UnsafeMutableRawPointer?
    /// idx 18: OrtApi::EnableCpuMemArena（未用，占位保布局）
    public var enableCpuMemArena: UnsafeMutableRawPointer?
    /// idx 19: OrtApi::DisableCpuMemArena（未用，占位保布局）
    public var disableCpuMemArena: UnsafeMutableRawPointer?
    /// idx 20: OrtApi::SetSessionLogId（未用，占位保布局）
    public var setSessionLogId: UnsafeMutableRawPointer?
    /// idx 21: OrtApi::SetSessionLogVerbosityLevel（未用，占位保布局）
    public var setSessionLogVerbosityLevel: UnsafeMutableRawPointer?
    /// idx 22: OrtApi::SetSessionLogSeverityLevel（未用，占位保布局）
    public var setSessionLogSeverityLevel: UnsafeMutableRawPointer?
    /// idx 23: OrtApi::SetSessionGraphOptimizationLevel
    public var setSessionGraphOptimizationLevel: (@convention(c) (UnsafeMutableRawPointer?, UInt32) -> UnsafeMutableRawPointer?)?
    /// idx 24: OrtApi::SetIntraOpNumThreads
    public var setIntraOpNumThreads: (@convention(c) (UnsafeMutableRawPointer?, Int32) -> UnsafeMutableRawPointer?)?
    /// idx 25: OrtApi::SetInterOpNumThreads（未用，占位保布局）
    public var setInterOpNumThreads: UnsafeMutableRawPointer?
    /// idx 26: OrtApi::CreateCustomOpDomain（未用，占位保布局）
    public var createCustomOpDomain: UnsafeMutableRawPointer?
    /// idx 27: OrtApi::CustomOpDomain_Add（未用，占位保布局）
    public var customOpDomain_Add: UnsafeMutableRawPointer?
    /// idx 28: OrtApi::AddCustomOpDomain（未用，占位保布局）
    public var addCustomOpDomain: UnsafeMutableRawPointer?
    /// idx 29: OrtApi::RegisterCustomOpsLibrary（未用，占位保布局）
    public var registerCustomOpsLibrary: UnsafeMutableRawPointer?
    /// idx 30: OrtApi::SessionGetInputCount（未用，占位保布局）
    public var sessionGetInputCount: UnsafeMutableRawPointer?
    /// idx 31: OrtApi::SessionGetOutputCount（未用，占位保布局）
    public var sessionGetOutputCount: UnsafeMutableRawPointer?
    /// idx 32: OrtApi::SessionGetOverridableInitializerCount（未用，占位保布局）
    public var sessionGetOverridableInitializerCount: UnsafeMutableRawPointer?
    /// idx 33: OrtApi::SessionGetInputTypeInfo（未用，占位保布局）
    public var sessionGetInputTypeInfo: UnsafeMutableRawPointer?
    /// idx 34: OrtApi::SessionGetOutputTypeInfo（未用，占位保布局）
    public var sessionGetOutputTypeInfo: UnsafeMutableRawPointer?
    /// idx 35: OrtApi::SessionGetOverridableInitializerTypeInfo（未用，占位保布局）
    public var sessionGetOverridableInitializerTypeInfo: UnsafeMutableRawPointer?
    /// idx 36: OrtApi::SessionGetInputName（未用，占位保布局）
    public var sessionGetInputName: UnsafeMutableRawPointer?
    /// idx 37: OrtApi::SessionGetOutputName（未用，占位保布局）
    public var sessionGetOutputName: UnsafeMutableRawPointer?
    /// idx 38: OrtApi::SessionGetOverridableInitializerName（未用，占位保布局）
    public var sessionGetOverridableInitializerName: UnsafeMutableRawPointer?
    /// idx 39: OrtApi::CreateRunOptions（未用，占位保布局）
    public var createRunOptions: UnsafeMutableRawPointer?
    /// idx 40: OrtApi::RunOptionsSetRunLogVerbosityLevel（未用，占位保布局）
    public var runOptionsSetRunLogVerbosityLevel: UnsafeMutableRawPointer?
    /// idx 41: OrtApi::RunOptionsSetRunLogSeverityLevel（未用，占位保布局）
    public var runOptionsSetRunLogSeverityLevel: UnsafeMutableRawPointer?
    /// idx 42: OrtApi::RunOptionsSetRunTag（未用，占位保布局）
    public var runOptionsSetRunTag: UnsafeMutableRawPointer?
    /// idx 43: OrtApi::RunOptionsGetRunLogVerbosityLevel（未用，占位保布局）
    public var runOptionsGetRunLogVerbosityLevel: UnsafeMutableRawPointer?
    /// idx 44: OrtApi::RunOptionsGetRunLogSeverityLevel（未用，占位保布局）
    public var runOptionsGetRunLogSeverityLevel: UnsafeMutableRawPointer?
    /// idx 45: OrtApi::RunOptionsGetRunTag（未用，占位保布局）
    public var runOptionsGetRunTag: UnsafeMutableRawPointer?
    /// idx 46: OrtApi::RunOptionsSetTerminate（未用，占位保布局）
    public var runOptionsSetTerminate: UnsafeMutableRawPointer?
    /// idx 47: OrtApi::RunOptionsUnsetTerminate（未用，占位保布局）
    public var runOptionsUnsetTerminate: UnsafeMutableRawPointer?
    /// idx 48: OrtApi::CreateTensorAsOrtValue（未用，占位保布局）
    public var createTensorAsOrtValue: UnsafeMutableRawPointer?
    /// idx 49: OrtApi::CreateTensorWithDataAsOrtValue
    public var createTensorWithDataAsOrtValue: (@convention(c) (UnsafeRawPointer?, UnsafeMutableRawPointer?, Int, UnsafePointer<Int64>?, Int, UInt32, UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 50: OrtApi::IsTensor（未用，占位保布局）
    public var isTensor: UnsafeMutableRawPointer?
    /// idx 51: OrtApi::GetTensorMutableData
    public var getTensorMutableData: (@convention(c) (UnsafeMutableRawPointer?, UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 52: OrtApi::FillStringTensor（未用，占位保布局）
    public var fillStringTensor: UnsafeMutableRawPointer?
    /// idx 53: OrtApi::GetStringTensorDataLength（未用，占位保布局）
    public var getStringTensorDataLength: UnsafeMutableRawPointer?
    /// idx 54: OrtApi::GetStringTensorContent（未用，占位保布局）
    public var getStringTensorContent: UnsafeMutableRawPointer?
    /// idx 55: OrtApi::CastTypeInfoToTensorInfo（未用，占位保布局）
    public var castTypeInfoToTensorInfo: UnsafeMutableRawPointer?
    /// idx 56: OrtApi::GetOnnxTypeFromTypeInfo（未用，占位保布局）
    public var getOnnxTypeFromTypeInfo: UnsafeMutableRawPointer?
    /// idx 57: OrtApi::CreateTensorTypeAndShapeInfo（未用，占位保布局）
    public var createTensorTypeAndShapeInfo: UnsafeMutableRawPointer?
    /// idx 58: OrtApi::SetTensorElementType（未用，占位保布局）
    public var setTensorElementType: UnsafeMutableRawPointer?
    /// idx 59: OrtApi::SetDimensions（未用，占位保布局）
    public var setDimensions: UnsafeMutableRawPointer?
    /// idx 60: OrtApi::GetTensorElementType（未用，占位保布局）
    public var getTensorElementType: UnsafeMutableRawPointer?
    /// idx 61: OrtApi::GetDimensionsCount
    public var getDimensionsCount: (@convention(c) (UnsafeRawPointer?, UnsafeMutablePointer<Int>?) -> UnsafeMutableRawPointer?)?
    /// idx 62: OrtApi::GetDimensions
    public var getDimensions: (@convention(c) (UnsafeRawPointer?, UnsafeMutablePointer<Int64>?, Int) -> UnsafeMutableRawPointer?)?
    /// idx 63: OrtApi::GetSymbolicDimensions（未用，占位保布局）
    public var getSymbolicDimensions: UnsafeMutableRawPointer?
    /// idx 64: OrtApi::GetTensorShapeElementCount（未用，占位保布局）
    public var getTensorShapeElementCount: UnsafeMutableRawPointer?
    /// idx 65: OrtApi::GetTensorTypeAndShape
    public var getTensorTypeAndShape: (@convention(c) (UnsafeRawPointer?, UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 66: OrtApi::GetTypeInfo（未用，占位保布局）
    public var getTypeInfo: UnsafeMutableRawPointer?
    /// idx 67: OrtApi::GetValueType（未用，占位保布局）
    public var getValueType: UnsafeMutableRawPointer?
    /// idx 68: OrtApi::CreateMemoryInfo（未用，占位保布局）
    public var createMemoryInfo: UnsafeMutableRawPointer?
    /// idx 69: OrtApi::CreateCpuMemoryInfo
    public var createCpuMemoryInfo: (@convention(c) (Int32, Int32, UnsafeMutablePointer<UnsafeMutableRawPointer?>?) -> UnsafeMutableRawPointer?)?
    /// idx 70: OrtApi::CompareMemoryInfo（未用，占位保布局）
    public var compareMemoryInfo: UnsafeMutableRawPointer?
    /// idx 71: OrtApi::MemoryInfoGetName（未用，占位保布局）
    public var memoryInfoGetName: UnsafeMutableRawPointer?
    /// idx 72: OrtApi::MemoryInfoGetId（未用，占位保布局）
    public var memoryInfoGetId: UnsafeMutableRawPointer?
    /// idx 73: OrtApi::MemoryInfoGetMemType（未用，占位保布局）
    public var memoryInfoGetMemType: UnsafeMutableRawPointer?
    /// idx 74: OrtApi::MemoryInfoGetType（未用，占位保布局）
    public var memoryInfoGetType: UnsafeMutableRawPointer?
    /// idx 75: OrtApi::AllocatorAlloc（未用，占位保布局）
    public var allocatorAlloc: UnsafeMutableRawPointer?
    /// idx 76: OrtApi::AllocatorFree（未用，占位保布局）
    public var allocatorFree: UnsafeMutableRawPointer?
    /// idx 77: OrtApi::AllocatorGetInfo（未用，占位保布局）
    public var allocatorGetInfo: UnsafeMutableRawPointer?
    /// idx 78: OrtApi::GetAllocatorWithDefaultOptions（未用，占位保布局）
    public var getAllocatorWithDefaultOptions: UnsafeMutableRawPointer?
    /// idx 79: OrtApi::AddFreeDimensionOverride（未用，占位保布局）
    public var addFreeDimensionOverride: UnsafeMutableRawPointer?
    /// idx 80: OrtApi::GetValue（未用，占位保布局）
    public var getValue: UnsafeMutableRawPointer?
    /// idx 81: OrtApi::GetValueCount（未用，占位保布局）
    public var getValueCount: UnsafeMutableRawPointer?
    /// idx 82: OrtApi::CreateValue（未用，占位保布局）
    public var createValue: UnsafeMutableRawPointer?
    /// idx 83: OrtApi::CreateOpaqueValue（未用，占位保布局）
    public var createOpaqueValue: UnsafeMutableRawPointer?
    /// idx 84: OrtApi::GetOpaqueValue（未用，占位保布局）
    public var getOpaqueValue: UnsafeMutableRawPointer?
    /// idx 85: OrtApi::KernelInfoGetAttribute_float（未用，占位保布局）
    public var kernelInfoGetAttribute_float: UnsafeMutableRawPointer?
    /// idx 86: OrtApi::KernelInfoGetAttribute_int64（未用，占位保布局）
    public var kernelInfoGetAttribute_int64: UnsafeMutableRawPointer?
    /// idx 87: OrtApi::KernelInfoGetAttribute_string（未用，占位保布局）
    public var kernelInfoGetAttribute_string: UnsafeMutableRawPointer?
    /// idx 88: OrtApi::KernelContext_GetInputCount（未用，占位保布局）
    public var kernelContext_GetInputCount: UnsafeMutableRawPointer?
    /// idx 89: OrtApi::KernelContext_GetOutputCount（未用，占位保布局）
    public var kernelContext_GetOutputCount: UnsafeMutableRawPointer?
    /// idx 90: OrtApi::KernelContext_GetInput（未用，占位保布局）
    public var kernelContext_GetInput: UnsafeMutableRawPointer?
    /// idx 91: OrtApi::KernelContext_GetOutput（未用，占位保布局）
    public var kernelContext_GetOutput: UnsafeMutableRawPointer?
    /// idx 92: OrtApi::ReleaseEnv
    public var releaseEnv: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?
    /// idx 93: OrtApi::ReleaseStatus
    public var releaseStatus: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?
    /// idx 94: OrtApi::ReleaseMemoryInfo
    public var releaseMemoryInfo: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?
    /// idx 95: OrtApi::ReleaseSession
    public var releaseSession: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?
    /// idx 96: OrtApi::ReleaseValue
    public var releaseValue: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?
    /// idx 97: OrtApi::ReleaseRunOptions（未用，占位保布局）
    public var releaseRunOptions: UnsafeMutableRawPointer?
    /// idx 98: OrtApi::ReleaseTypeInfo（未用，占位保布局）
    public var releaseTypeInfo: UnsafeMutableRawPointer?
    /// idx 99: OrtApi::ReleaseTensorTypeAndShapeInfo
    public var releaseTensorTypeAndShapeInfo: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?
    /// idx 100: OrtApi::ReleaseSessionOptions
    public var releaseSessionOptions: (@convention(c) (UnsafeMutableRawPointer?) -> Void)?
    /// idx 101: OrtApi::ReleaseCustomOpDomain（未用，占位保布局）
    public var releaseCustomOpDomain: UnsafeMutableRawPointer?
    /// idx 102: OrtApi::GetDenotationFromTypeInfo（未用，占位保布局）
    public var getDenotationFromTypeInfo: UnsafeMutableRawPointer?
    /// idx 103: OrtApi::CastTypeInfoToMapTypeInfo（未用，占位保布局）
    public var castTypeInfoToMapTypeInfo: UnsafeMutableRawPointer?
    /// idx 104: OrtApi::CastTypeInfoToSequenceTypeInfo（未用，占位保布局）
    public var castTypeInfoToSequenceTypeInfo: UnsafeMutableRawPointer?
    /// idx 105: OrtApi::GetMapKeyType（未用，占位保布局）
    public var getMapKeyType: UnsafeMutableRawPointer?
    /// idx 106: OrtApi::GetMapValueType（未用，占位保布局）
    public var getMapValueType: UnsafeMutableRawPointer?
    /// idx 107: OrtApi::GetSequenceElementType（未用，占位保布局）
    public var getSequenceElementType: UnsafeMutableRawPointer?
    /// idx 108: OrtApi::ReleaseMapTypeInfo（未用，占位保布局）
    public var releaseMapTypeInfo: UnsafeMutableRawPointer?
    /// idx 109: OrtApi::ReleaseSequenceTypeInfo（未用，占位保布局）
    public var releaseSequenceTypeInfo: UnsafeMutableRawPointer?
    /// idx 110: OrtApi::SessionEndProfiling（未用，占位保布局）
    public var sessionEndProfiling: UnsafeMutableRawPointer?
    /// idx 111: OrtApi::SessionGetModelMetadata（未用，占位保布局）
    public var sessionGetModelMetadata: UnsafeMutableRawPointer?
    /// idx 112: OrtApi::ModelMetadataGetProducerName（未用，占位保布局）
    public var modelMetadataGetProducerName: UnsafeMutableRawPointer?
    /// idx 113: OrtApi::ModelMetadataGetGraphName（未用，占位保布局）
    public var modelMetadataGetGraphName: UnsafeMutableRawPointer?
    /// idx 114: OrtApi::ModelMetadataGetDomain（未用，占位保布局）
    public var modelMetadataGetDomain: UnsafeMutableRawPointer?
    /// idx 115: OrtApi::ModelMetadataGetDescription（未用，占位保布局）
    public var modelMetadataGetDescription: UnsafeMutableRawPointer?
    /// idx 116: OrtApi::ModelMetadataLookupCustomMetadataMap（未用，占位保布局）
    public var modelMetadataLookupCustomMetadataMap: UnsafeMutableRawPointer?
    /// idx 117: OrtApi::ModelMetadataGetVersion（未用，占位保布局）
    public var modelMetadataGetVersion: UnsafeMutableRawPointer?
    /// idx 118: OrtApi::ReleaseModelMetadata（未用，占位保布局）
    public var releaseModelMetadata: UnsafeMutableRawPointer?
    /// idx 119: OrtApi::CreateEnvWithGlobalThreadPools（未用，占位保布局）
    public var createEnvWithGlobalThreadPools: UnsafeMutableRawPointer?
    /// idx 120: OrtApi::DisablePerSessionThreads（未用，占位保布局）
    public var disablePerSessionThreads: UnsafeMutableRawPointer?
    /// idx 121: OrtApi::CreateThreadingOptions（未用，占位保布局）
    public var createThreadingOptions: UnsafeMutableRawPointer?
    /// idx 122: OrtApi::ReleaseThreadingOptions（未用，占位保布局）
    public var releaseThreadingOptions: UnsafeMutableRawPointer?
    /// idx 123: OrtApi::ModelMetadataGetCustomMetadataMapKeys（未用，占位保布局）
    public var modelMetadataGetCustomMetadataMapKeys: UnsafeMutableRawPointer?
    /// idx 124: OrtApi::AddFreeDimensionOverrideByName（未用，占位保布局）
    public var addFreeDimensionOverrideByName: UnsafeMutableRawPointer?
    /// idx 125: OrtApi::GetAvailableProviders（未用，占位保布局）
    public var getAvailableProviders: UnsafeMutableRawPointer?
    /// idx 126: OrtApi::ReleaseAvailableProviders（未用，占位保布局）
    public var releaseAvailableProviders: UnsafeMutableRawPointer?
    /// idx 127: OrtApi::GetStringTensorElementLength（未用，占位保布局）
    public var getStringTensorElementLength: UnsafeMutableRawPointer?
    /// idx 128: OrtApi::GetStringTensorElement（未用，占位保布局）
    public var getStringTensorElement: UnsafeMutableRawPointer?
    /// idx 129: OrtApi::FillStringTensorElement（未用，占位保布局）
    public var fillStringTensorElement: UnsafeMutableRawPointer?
    /// idx 130: OrtApi::AddSessionConfigEntry（未用，占位保布局）
    public var addSessionConfigEntry: UnsafeMutableRawPointer?
    /// idx 131: OrtApi::CreateAllocator（未用，占位保布局）
    public var createAllocator: UnsafeMutableRawPointer?
    /// idx 132: OrtApi::ReleaseAllocator（未用，占位保布局）
    public var releaseAllocator: UnsafeMutableRawPointer?
    /// idx 133: OrtApi::RunWithBinding（未用，占位保布局）
    public var runWithBinding: UnsafeMutableRawPointer?
    /// idx 134: OrtApi::CreateIoBinding（未用，占位保布局）
    public var createIoBinding: UnsafeMutableRawPointer?
    /// idx 135: OrtApi::ReleaseIoBinding（未用，占位保布局）
    public var releaseIoBinding: UnsafeMutableRawPointer?
    /// idx 136: OrtApi::BindInput（未用，占位保布局）
    public var bindInput: UnsafeMutableRawPointer?
    /// idx 137: OrtApi::BindOutput（未用，占位保布局）
    public var bindOutput: UnsafeMutableRawPointer?
    /// idx 138: OrtApi::BindOutputToDevice（未用，占位保布局）
    public var bindOutputToDevice: UnsafeMutableRawPointer?
    /// idx 139: OrtApi::GetBoundOutputNames（未用，占位保布局）
    public var getBoundOutputNames: UnsafeMutableRawPointer?
    /// idx 140: OrtApi::GetBoundOutputValues（未用，占位保布局）
    public var getBoundOutputValues: UnsafeMutableRawPointer?
    /// idx 141: OrtApi::ClearBoundInputs（未用，占位保布局）
    public var clearBoundInputs: UnsafeMutableRawPointer?
    /// idx 142: OrtApi::ClearBoundOutputs（未用，占位保布局）
    public var clearBoundOutputs: UnsafeMutableRawPointer?
    /// idx 143: OrtApi::TensorAt（未用，占位保布局）
    public var tensorAt: UnsafeMutableRawPointer?
    /// idx 144: OrtApi::CreateAndRegisterAllocator（未用，占位保布局）
    public var createAndRegisterAllocator: UnsafeMutableRawPointer?
    /// idx 145: OrtApi::SetLanguageProjection（未用，占位保布局）
    public var setLanguageProjection: UnsafeMutableRawPointer?
    /// idx 146: OrtApi::SessionGetProfilingStartTimeNs（未用，占位保布局）
    public var sessionGetProfilingStartTimeNs: UnsafeMutableRawPointer?
    /// idx 147: OrtApi::SetGlobalIntraOpNumThreads（未用，占位保布局）
    public var setGlobalIntraOpNumThreads: UnsafeMutableRawPointer?
    /// idx 148: OrtApi::SetGlobalInterOpNumThreads（未用，占位保布局）
    public var setGlobalInterOpNumThreads: UnsafeMutableRawPointer?
    /// idx 149: OrtApi::SetGlobalSpinControl（未用，占位保布局）
    public var setGlobalSpinControl: UnsafeMutableRawPointer?
    /// idx 150: OrtApi::AddInitializer（未用，占位保布局）
    public var addInitializer: UnsafeMutableRawPointer?
    /// idx 151: OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools（未用，占位保布局）
    public var createEnvWithCustomLoggerAndGlobalThreadPools: UnsafeMutableRawPointer?
    /// idx 152: OrtApi::SessionOptionsAppendExecutionProvider_CUDA（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_CUDA: UnsafeMutableRawPointer?
    /// idx 153: OrtApi::SessionOptionsAppendExecutionProvider_ROCM（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_ROCM: UnsafeMutableRawPointer?
    /// idx 154: OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_OpenVINO: UnsafeMutableRawPointer?
    /// idx 155: OrtApi::SetGlobalDenormalAsZero（未用，占位保布局）
    public var setGlobalDenormalAsZero: UnsafeMutableRawPointer?
    /// idx 156: OrtApi::CreateArenaCfg（未用，占位保布局）
    public var createArenaCfg: UnsafeMutableRawPointer?
    /// idx 157: OrtApi::ReleaseArenaCfg（未用，占位保布局）
    public var releaseArenaCfg: UnsafeMutableRawPointer?
    /// idx 158: OrtApi::ModelMetadataGetGraphDescription（未用，占位保布局）
    public var modelMetadataGetGraphDescription: UnsafeMutableRawPointer?
    /// idx 159: OrtApi::SessionOptionsAppendExecutionProvider_TensorRT（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_TensorRT: UnsafeMutableRawPointer?
    /// idx 160: OrtApi::SetCurrentGpuDeviceId（未用，占位保布局）
    public var setCurrentGpuDeviceId: UnsafeMutableRawPointer?
    /// idx 161: OrtApi::GetCurrentGpuDeviceId（未用，占位保布局）
    public var getCurrentGpuDeviceId: UnsafeMutableRawPointer?
    /// idx 162: OrtApi::KernelInfoGetAttributeArray_float（未用，占位保布局）
    public var kernelInfoGetAttributeArray_float: UnsafeMutableRawPointer?
    /// idx 163: OrtApi::KernelInfoGetAttributeArray_int64（未用，占位保布局）
    public var kernelInfoGetAttributeArray_int64: UnsafeMutableRawPointer?
    /// idx 164: OrtApi::CreateArenaCfgV2（未用，占位保布局）
    public var createArenaCfgV2: UnsafeMutableRawPointer?
    /// idx 165: OrtApi::AddRunConfigEntry（未用，占位保布局）
    public var addRunConfigEntry: UnsafeMutableRawPointer?
    /// idx 166: OrtApi::CreatePrepackedWeightsContainer（未用，占位保布局）
    public var createPrepackedWeightsContainer: UnsafeMutableRawPointer?
    /// idx 167: OrtApi::ReleasePrepackedWeightsContainer（未用，占位保布局）
    public var releasePrepackedWeightsContainer: UnsafeMutableRawPointer?
    /// idx 168: OrtApi::CreateSessionWithPrepackedWeightsContainer（未用，占位保布局）
    public var createSessionWithPrepackedWeightsContainer: UnsafeMutableRawPointer?
    /// idx 169: OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer（未用，占位保布局）
    public var createSessionFromArrayWithPrepackedWeightsContainer: UnsafeMutableRawPointer?
    /// idx 170: OrtApi::SessionOptionsAppendExecutionProvider_TensorRT_V2（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_TensorRT_V2: UnsafeMutableRawPointer?
    /// idx 171: OrtApi::CreateTensorRTProviderOptions（未用，占位保布局）
    public var createTensorRTProviderOptions: UnsafeMutableRawPointer?
    /// idx 172: OrtApi::UpdateTensorRTProviderOptions（未用，占位保布局）
    public var updateTensorRTProviderOptions: UnsafeMutableRawPointer?
    /// idx 173: OrtApi::GetTensorRTProviderOptionsAsString（未用，占位保布局）
    public var getTensorRTProviderOptionsAsString: UnsafeMutableRawPointer?
    /// idx 174: OrtApi::ReleaseTensorRTProviderOptions（未用，占位保布局）
    public var releaseTensorRTProviderOptions: UnsafeMutableRawPointer?
    /// idx 175: OrtApi::EnableOrtCustomOps（未用，占位保布局）
    public var enableOrtCustomOps: UnsafeMutableRawPointer?
    /// idx 176: OrtApi::RegisterAllocator（未用，占位保布局）
    public var registerAllocator: UnsafeMutableRawPointer?
    /// idx 177: OrtApi::UnregisterAllocator（未用，占位保布局）
    public var unregisterAllocator: UnsafeMutableRawPointer?
    /// idx 178: OrtApi::IsSparseTensor（未用，占位保布局）
    public var isSparseTensor: UnsafeMutableRawPointer?
    /// idx 179: OrtApi::CreateSparseTensorAsOrtValue（未用，占位保布局）
    public var createSparseTensorAsOrtValue: UnsafeMutableRawPointer?
    /// idx 180: OrtApi::FillSparseTensorCoo（未用，占位保布局）
    public var fillSparseTensorCoo: UnsafeMutableRawPointer?
    /// idx 181: OrtApi::FillSparseTensorCsr（未用，占位保布局）
    public var fillSparseTensorCsr: UnsafeMutableRawPointer?
    /// idx 182: OrtApi::FillSparseTensorBlockSparse（未用，占位保布局）
    public var fillSparseTensorBlockSparse: UnsafeMutableRawPointer?
    /// idx 183: OrtApi::CreateSparseTensorWithValuesAsOrtValue（未用，占位保布局）
    public var createSparseTensorWithValuesAsOrtValue: UnsafeMutableRawPointer?
    /// idx 184: OrtApi::UseCooIndices（未用，占位保布局）
    public var useCooIndices: UnsafeMutableRawPointer?
    /// idx 185: OrtApi::UseCsrIndices（未用，占位保布局）
    public var useCsrIndices: UnsafeMutableRawPointer?
    /// idx 186: OrtApi::UseBlockSparseIndices（未用，占位保布局）
    public var useBlockSparseIndices: UnsafeMutableRawPointer?
    /// idx 187: OrtApi::GetSparseTensorFormat（未用，占位保布局）
    public var getSparseTensorFormat: UnsafeMutableRawPointer?
    /// idx 188: OrtApi::GetSparseTensorValuesTypeAndShape（未用，占位保布局）
    public var getSparseTensorValuesTypeAndShape: UnsafeMutableRawPointer?
    /// idx 189: OrtApi::GetSparseTensorValues（未用，占位保布局）
    public var getSparseTensorValues: UnsafeMutableRawPointer?
    /// idx 190: OrtApi::GetSparseTensorIndicesTypeShape（未用，占位保布局）
    public var getSparseTensorIndicesTypeShape: UnsafeMutableRawPointer?
    /// idx 191: OrtApi::GetSparseTensorIndices（未用，占位保布局）
    public var getSparseTensorIndices: UnsafeMutableRawPointer?
    /// idx 192: OrtApi::HasValue（未用，占位保布局）
    public var hasValue: UnsafeMutableRawPointer?
    /// idx 193: OrtApi::KernelContext_GetGPUComputeStream（未用，占位保布局）
    public var kernelContext_GetGPUComputeStream: UnsafeMutableRawPointer?
    /// idx 194: OrtApi::GetTensorMemoryInfo（未用，占位保布局）
    public var getTensorMemoryInfo: UnsafeMutableRawPointer?
    /// idx 195: OrtApi::GetExecutionProviderApi（未用，占位保布局）
    public var getExecutionProviderApi: UnsafeMutableRawPointer?
    /// idx 196: OrtApi::SessionOptionsSetCustomCreateThreadFn（未用，占位保布局）
    public var sessionOptionsSetCustomCreateThreadFn: UnsafeMutableRawPointer?
    /// idx 197: OrtApi::SessionOptionsSetCustomThreadCreationOptions（未用，占位保布局）
    public var sessionOptionsSetCustomThreadCreationOptions: UnsafeMutableRawPointer?
    /// idx 198: OrtApi::SessionOptionsSetCustomJoinThreadFn（未用，占位保布局）
    public var sessionOptionsSetCustomJoinThreadFn: UnsafeMutableRawPointer?
    /// idx 199: OrtApi::SetGlobalCustomCreateThreadFn（未用，占位保布局）
    public var setGlobalCustomCreateThreadFn: UnsafeMutableRawPointer?
    /// idx 200: OrtApi::SetGlobalCustomThreadCreationOptions（未用，占位保布局）
    public var setGlobalCustomThreadCreationOptions: UnsafeMutableRawPointer?
    /// idx 201: OrtApi::SetGlobalCustomJoinThreadFn（未用，占位保布局）
    public var setGlobalCustomJoinThreadFn: UnsafeMutableRawPointer?
    /// idx 202: OrtApi::SynchronizeBoundInputs（未用，占位保布局）
    public var synchronizeBoundInputs: UnsafeMutableRawPointer?
    /// idx 203: OrtApi::SynchronizeBoundOutputs（未用，占位保布局）
    public var synchronizeBoundOutputs: UnsafeMutableRawPointer?
    /// idx 204: OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_CUDA_V2: UnsafeMutableRawPointer?
    /// idx 205: OrtApi::CreateCUDAProviderOptions（未用，占位保布局）
    public var createCUDAProviderOptions: UnsafeMutableRawPointer?
    /// idx 206: OrtApi::UpdateCUDAProviderOptions（未用，占位保布局）
    public var updateCUDAProviderOptions: UnsafeMutableRawPointer?
    /// idx 207: OrtApi::GetCUDAProviderOptionsAsString（未用，占位保布局）
    public var getCUDAProviderOptionsAsString: UnsafeMutableRawPointer?
    /// idx 208: OrtApi::ReleaseCUDAProviderOptions（未用，占位保布局）
    public var releaseCUDAProviderOptions: UnsafeMutableRawPointer?
    /// idx 209: OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_MIGraphX: UnsafeMutableRawPointer?
    /// idx 210: OrtApi::AddExternalInitializers（未用，占位保布局）
    public var addExternalInitializers: UnsafeMutableRawPointer?
    /// idx 211: OrtApi::CreateOpAttr（未用，占位保布局）
    public var createOpAttr: UnsafeMutableRawPointer?
    /// idx 212: OrtApi::ReleaseOpAttr（未用，占位保布局）
    public var releaseOpAttr: UnsafeMutableRawPointer?
    /// idx 213: OrtApi::CreateOp（未用，占位保布局）
    public var createOp: UnsafeMutableRawPointer?
    /// idx 214: OrtApi::InvokeOp（未用，占位保布局）
    public var invokeOp: UnsafeMutableRawPointer?
    /// idx 215: OrtApi::ReleaseOp（未用，占位保布局）
    public var releaseOp: UnsafeMutableRawPointer?
    /// idx 216: OrtApi::SessionOptionsAppendExecutionProvider（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider: UnsafeMutableRawPointer?
    /// idx 217: OrtApi::CopyKernelInfo（未用，占位保布局）
    public var copyKernelInfo: UnsafeMutableRawPointer?
    /// idx 218: OrtApi::ReleaseKernelInfo（未用，占位保布局）
    public var releaseKernelInfo: UnsafeMutableRawPointer?
    /// idx 219: OrtApi::GetTrainingApi（未用，占位保布局）
    public var getTrainingApi: UnsafeMutableRawPointer?
    /// idx 220: OrtApi::SessionOptionsAppendExecutionProvider_CANN（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_CANN: UnsafeMutableRawPointer?
    /// idx 221: OrtApi::CreateCANNProviderOptions（未用，占位保布局）
    public var createCANNProviderOptions: UnsafeMutableRawPointer?
    /// idx 222: OrtApi::UpdateCANNProviderOptions（未用，占位保布局）
    public var updateCANNProviderOptions: UnsafeMutableRawPointer?
    /// idx 223: OrtApi::GetCANNProviderOptionsAsString（未用，占位保布局）
    public var getCANNProviderOptionsAsString: UnsafeMutableRawPointer?
    /// idx 224: OrtApi::ReleaseCANNProviderOptions（未用，占位保布局）
    public var releaseCANNProviderOptions: UnsafeMutableRawPointer?
    /// idx 225: OrtApi::MemoryInfoGetDeviceType（未用，占位保布局）
    public var memoryInfoGetDeviceType: UnsafeMutableRawPointer?
    /// idx 226: OrtApi::UpdateEnvWithCustomLogLevel（未用，占位保布局）
    public var updateEnvWithCustomLogLevel: UnsafeMutableRawPointer?
    /// idx 227: OrtApi::SetGlobalIntraOpThreadAffinity（未用，占位保布局）
    public var setGlobalIntraOpThreadAffinity: UnsafeMutableRawPointer?
    /// idx 228: OrtApi::RegisterCustomOpsLibrary_V2（未用，占位保布局）
    public var registerCustomOpsLibrary_V2: UnsafeMutableRawPointer?
    /// idx 229: OrtApi::RegisterCustomOpsUsingFunction（未用，占位保布局）
    public var registerCustomOpsUsingFunction: UnsafeMutableRawPointer?
    /// idx 230: OrtApi::KernelInfo_GetInputCount（未用，占位保布局）
    public var kernelInfo_GetInputCount: UnsafeMutableRawPointer?
    /// idx 231: OrtApi::KernelInfo_GetOutputCount（未用，占位保布局）
    public var kernelInfo_GetOutputCount: UnsafeMutableRawPointer?
    /// idx 232: OrtApi::KernelInfo_GetInputName（未用，占位保布局）
    public var kernelInfo_GetInputName: UnsafeMutableRawPointer?
    /// idx 233: OrtApi::KernelInfo_GetOutputName（未用，占位保布局）
    public var kernelInfo_GetOutputName: UnsafeMutableRawPointer?
    /// idx 234: OrtApi::KernelInfo_GetInputTypeInfo（未用，占位保布局）
    public var kernelInfo_GetInputTypeInfo: UnsafeMutableRawPointer?
    /// idx 235: OrtApi::KernelInfo_GetOutputTypeInfo（未用，占位保布局）
    public var kernelInfo_GetOutputTypeInfo: UnsafeMutableRawPointer?
    /// idx 236: OrtApi::KernelInfoGetAttribute_tensor（未用，占位保布局）
    public var kernelInfoGetAttribute_tensor: UnsafeMutableRawPointer?
    /// idx 237: OrtApi::HasSessionConfigEntry（未用，占位保布局）
    public var hasSessionConfigEntry: UnsafeMutableRawPointer?
    /// idx 238: OrtApi::GetSessionConfigEntry（未用，占位保布局）
    public var getSessionConfigEntry: UnsafeMutableRawPointer?
    /// idx 239: OrtApi::SessionOptionsAppendExecutionProvider_Dnnl（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_Dnnl: UnsafeMutableRawPointer?
    /// idx 240: OrtApi::CreateDnnlProviderOptions（未用，占位保布局）
    public var createDnnlProviderOptions: UnsafeMutableRawPointer?
    /// idx 241: OrtApi::UpdateDnnlProviderOptions（未用，占位保布局）
    public var updateDnnlProviderOptions: UnsafeMutableRawPointer?
    /// idx 242: OrtApi::GetDnnlProviderOptionsAsString（未用，占位保布局）
    public var getDnnlProviderOptionsAsString: UnsafeMutableRawPointer?
    /// idx 243: OrtApi::ReleaseDnnlProviderOptions（未用，占位保布局）
    public var releaseDnnlProviderOptions: UnsafeMutableRawPointer?
    /// idx 244: OrtApi::KernelInfo_GetNodeName（未用，占位保布局）
    public var kernelInfo_GetNodeName: UnsafeMutableRawPointer?
    /// idx 245: OrtApi::KernelInfo_GetLogger（未用，占位保布局）
    public var kernelInfo_GetLogger: UnsafeMutableRawPointer?
    /// idx 246: OrtApi::KernelContext_GetLogger（未用，占位保布局）
    public var kernelContext_GetLogger: UnsafeMutableRawPointer?
    /// idx 247: OrtApi::Logger_LogMessage（未用，占位保布局）
    public var logger_LogMessage: UnsafeMutableRawPointer?
    /// idx 248: OrtApi::Logger_GetLoggingSeverityLevel（未用，占位保布局）
    public var logger_GetLoggingSeverityLevel: UnsafeMutableRawPointer?
    /// idx 249: OrtApi::KernelInfoGetConstantInput_tensor（未用，占位保布局）
    public var kernelInfoGetConstantInput_tensor: UnsafeMutableRawPointer?
    /// idx 250: OrtApi::CastTypeInfoToOptionalTypeInfo（未用，占位保布局）
    public var castTypeInfoToOptionalTypeInfo: UnsafeMutableRawPointer?
    /// idx 251: OrtApi::GetOptionalContainedTypeInfo（未用，占位保布局）
    public var getOptionalContainedTypeInfo: UnsafeMutableRawPointer?
    /// idx 252: OrtApi::GetResizedStringTensorElementBuffer（未用，占位保布局）
    public var getResizedStringTensorElementBuffer: UnsafeMutableRawPointer?
    /// idx 253: OrtApi::KernelContext_GetAllocator（未用，占位保布局）
    public var kernelContext_GetAllocator: UnsafeMutableRawPointer?
    /// idx 254: OrtApi::GetBuildInfoString（未用，占位保布局）
    public var getBuildInfoString: UnsafeMutableRawPointer?
    /// idx 255: OrtApi::CreateROCMProviderOptions（未用，占位保布局）
    public var createROCMProviderOptions: UnsafeMutableRawPointer?
    /// idx 256: OrtApi::UpdateROCMProviderOptions（未用，占位保布局）
    public var updateROCMProviderOptions: UnsafeMutableRawPointer?
    /// idx 257: OrtApi::GetROCMProviderOptionsAsString（未用，占位保布局）
    public var getROCMProviderOptionsAsString: UnsafeMutableRawPointer?
    /// idx 258: OrtApi::ReleaseROCMProviderOptions（未用，占位保布局）
    public var releaseROCMProviderOptions: UnsafeMutableRawPointer?
    /// idx 259: OrtApi::CreateAndRegisterAllocatorV2（未用，占位保布局）
    public var createAndRegisterAllocatorV2: UnsafeMutableRawPointer?
    /// idx 260: OrtApi::RunAsync（未用，占位保布局）
    public var runAsync: UnsafeMutableRawPointer?
    /// idx 261: OrtApi::UpdateTensorRTProviderOptionsWithValue（未用，占位保布局）
    public var updateTensorRTProviderOptionsWithValue: UnsafeMutableRawPointer?
    /// idx 262: OrtApi::GetTensorRTProviderOptionsByName（未用，占位保布局）
    public var getTensorRTProviderOptionsByName: UnsafeMutableRawPointer?
    /// idx 263: OrtApi::UpdateCUDAProviderOptionsWithValue（未用，占位保布局）
    public var updateCUDAProviderOptionsWithValue: UnsafeMutableRawPointer?
    /// idx 264: OrtApi::GetCUDAProviderOptionsByName（未用，占位保布局）
    public var getCUDAProviderOptionsByName: UnsafeMutableRawPointer?
    /// idx 265: OrtApi::KernelContext_GetResource（未用，占位保布局）
    public var kernelContext_GetResource: UnsafeMutableRawPointer?
    /// idx 266: OrtApi::SetUserLoggingFunction（未用，占位保布局）
    public var setUserLoggingFunction: UnsafeMutableRawPointer?
    /// idx 267: OrtApi::ShapeInferContext_GetInputCount（未用，占位保布局）
    public var shapeInferContext_GetInputCount: UnsafeMutableRawPointer?
    /// idx 268: OrtApi::ShapeInferContext_GetInputTypeShape（未用，占位保布局）
    public var shapeInferContext_GetInputTypeShape: UnsafeMutableRawPointer?
    /// idx 269: OrtApi::ShapeInferContext_GetAttribute（未用，占位保布局）
    public var shapeInferContext_GetAttribute: UnsafeMutableRawPointer?
    /// idx 270: OrtApi::ShapeInferContext_SetOutputTypeShape（未用，占位保布局）
    public var shapeInferContext_SetOutputTypeShape: UnsafeMutableRawPointer?
    /// idx 271: OrtApi::SetSymbolicDimensions（未用，占位保布局）
    public var setSymbolicDimensions: UnsafeMutableRawPointer?
    /// idx 272: OrtApi::ReadOpAttr（未用，占位保布局）
    public var readOpAttr: UnsafeMutableRawPointer?
    /// idx 273: OrtApi::SetDeterministicCompute（未用，占位保布局）
    public var setDeterministicCompute: UnsafeMutableRawPointer?
    /// idx 274: OrtApi::KernelContext_ParallelFor（未用，占位保布局）
    public var kernelContext_ParallelFor: UnsafeMutableRawPointer?
    /// idx 275: OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO_V2（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_OpenVINO_V2: UnsafeMutableRawPointer?
    /// idx 276: OrtApi::SessionOptionsAppendExecutionProvider_VitisAI（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_VitisAI: UnsafeMutableRawPointer?
    /// idx 277: OrtApi::KernelContext_GetScratchBuffer（未用，占位保布局）
    public var kernelContext_GetScratchBuffer: UnsafeMutableRawPointer?
    /// idx 278: OrtApi::KernelInfoGetAllocator（未用，占位保布局）
    public var kernelInfoGetAllocator: UnsafeMutableRawPointer?
    /// idx 279: OrtApi::AddExternalInitializersFromFilesInMemory（未用，占位保布局）
    public var addExternalInitializersFromFilesInMemory: UnsafeMutableRawPointer?
    /// idx 280: OrtApi::CreateLoraAdapter（未用，占位保布局）
    public var createLoraAdapter: UnsafeMutableRawPointer?
    /// idx 281: OrtApi::CreateLoraAdapterFromArray（未用，占位保布局）
    public var createLoraAdapterFromArray: UnsafeMutableRawPointer?
    /// idx 282: OrtApi::ReleaseLoraAdapter（未用，占位保布局）
    public var releaseLoraAdapter: UnsafeMutableRawPointer?
    /// idx 283: OrtApi::RunOptionsAddActiveLoraAdapter（未用，占位保布局）
    public var runOptionsAddActiveLoraAdapter: UnsafeMutableRawPointer?
    /// idx 284: OrtApi::SetEpDynamicOptions（未用，占位保布局）
    public var setEpDynamicOptions: UnsafeMutableRawPointer?
    /// idx 285: OrtApi::ReleaseValueInfo（未用，占位保布局）
    public var releaseValueInfo: UnsafeMutableRawPointer?
    /// idx 286: OrtApi::ReleaseNode（未用，占位保布局）
    public var releaseNode: UnsafeMutableRawPointer?
    /// idx 287: OrtApi::ReleaseGraph（未用，占位保布局）
    public var releaseGraph: UnsafeMutableRawPointer?
    /// idx 288: OrtApi::ReleaseModel（未用，占位保布局）
    public var releaseModel: UnsafeMutableRawPointer?
    /// idx 289: OrtApi::GetValueInfoName（未用，占位保布局）
    public var getValueInfoName: UnsafeMutableRawPointer?
    /// idx 290: OrtApi::GetValueInfoTypeInfo（未用，占位保布局）
    public var getValueInfoTypeInfo: UnsafeMutableRawPointer?
    /// idx 291: OrtApi::GetModelEditorApi（未用，占位保布局）
    public var getModelEditorApi: UnsafeMutableRawPointer?
    /// idx 292: OrtApi::CreateTensorWithDataAndDeleterAsOrtValue（未用，占位保布局）
    public var createTensorWithDataAndDeleterAsOrtValue: UnsafeMutableRawPointer?
    /// idx 293: OrtApi::SessionOptionsSetLoadCancellationFlag（未用，占位保布局）
    public var sessionOptionsSetLoadCancellationFlag: UnsafeMutableRawPointer?
    /// idx 294: OrtApi::GetCompileApi（未用，占位保布局）
    public var getCompileApi: UnsafeMutableRawPointer?
    /// idx 295: OrtApi::CreateKeyValuePairs（未用，占位保布局）
    public var createKeyValuePairs: UnsafeMutableRawPointer?
    /// idx 296: OrtApi::AddKeyValuePair（未用，占位保布局）
    public var addKeyValuePair: UnsafeMutableRawPointer?
    /// idx 297: OrtApi::GetKeyValue（未用，占位保布局）
    public var getKeyValue: UnsafeMutableRawPointer?
    /// idx 298: OrtApi::GetKeyValuePairs（未用，占位保布局）
    public var getKeyValuePairs: UnsafeMutableRawPointer?
    /// idx 299: OrtApi::RemoveKeyValuePair（未用，占位保布局）
    public var removeKeyValuePair: UnsafeMutableRawPointer?
    /// idx 300: OrtApi::ReleaseKeyValuePairs（未用，占位保布局）
    public var releaseKeyValuePairs: UnsafeMutableRawPointer?
    /// idx 301: OrtApi::RegisterExecutionProviderLibrary（未用，占位保布局）
    public var registerExecutionProviderLibrary: UnsafeMutableRawPointer?
    /// idx 302: OrtApi::UnregisterExecutionProviderLibrary（未用，占位保布局）
    public var unregisterExecutionProviderLibrary: UnsafeMutableRawPointer?
    /// idx 303: OrtApi::GetEpDevices（未用，占位保布局）
    public var getEpDevices: UnsafeMutableRawPointer?
    /// idx 304: OrtApi::SessionOptionsAppendExecutionProvider_V2（未用，占位保布局）
    public var sessionOptionsAppendExecutionProvider_V2: UnsafeMutableRawPointer?
    /// idx 305: OrtApi::SessionOptionsSetEpSelectionPolicy（未用，占位保布局）
    public var sessionOptionsSetEpSelectionPolicy: UnsafeMutableRawPointer?
    /// idx 306: OrtApi::SessionOptionsSetEpSelectionPolicyDelegate（未用，占位保布局）
    public var sessionOptionsSetEpSelectionPolicyDelegate: UnsafeMutableRawPointer?
    /// idx 307: OrtApi::HardwareDevice_Type（未用，占位保布局）
    public var hardwareDevice_Type: UnsafeMutableRawPointer?
    /// idx 308: OrtApi::HardwareDevice_VendorId（未用，占位保布局）
    public var hardwareDevice_VendorId: UnsafeMutableRawPointer?
    /// idx 309: OrtApi::HardwareDevice_Vendor（未用，占位保布局）
    public var hardwareDevice_Vendor: UnsafeMutableRawPointer?
    /// idx 310: OrtApi::HardwareDevice_DeviceId（未用，占位保布局）
    public var hardwareDevice_DeviceId: UnsafeMutableRawPointer?
    /// idx 311: OrtApi::HardwareDevice_Metadata（未用，占位保布局）
    public var hardwareDevice_Metadata: UnsafeMutableRawPointer?
    /// idx 312: OrtApi::EpDevice_EpName（未用，占位保布局）
    public var epDevice_EpName: UnsafeMutableRawPointer?
    /// idx 313: OrtApi::EpDevice_EpVendor（未用，占位保布局）
    public var epDevice_EpVendor: UnsafeMutableRawPointer?
    /// idx 314: OrtApi::EpDevice_EpMetadata（未用，占位保布局）
    public var epDevice_EpMetadata: UnsafeMutableRawPointer?
    /// idx 315: OrtApi::EpDevice_EpOptions（未用，占位保布局）
    public var epDevice_EpOptions: UnsafeMutableRawPointer?
    /// idx 316: OrtApi::EpDevice_Device（未用，占位保布局）
    public var epDevice_Device: UnsafeMutableRawPointer?
    /// idx 317: OrtApi::GetEpApi（未用，占位保布局）
    public var getEpApi: UnsafeMutableRawPointer?
    /// idx 318: OrtApi::GetTensorSizeInBytes（未用，占位保布局）
    public var getTensorSizeInBytes: UnsafeMutableRawPointer?
    /// idx 319: OrtApi::AllocatorGetStats（未用，占位保布局）
    public var allocatorGetStats: UnsafeMutableRawPointer?
    /// idx 320: OrtApi::CreateMemoryInfo_V2（未用，占位保布局）
    public var createMemoryInfo_V2: UnsafeMutableRawPointer?
    /// idx 321: OrtApi::MemoryInfoGetDeviceMemType（未用，占位保布局）
    public var memoryInfoGetDeviceMemType: UnsafeMutableRawPointer?
    /// idx 322: OrtApi::MemoryInfoGetVendorId（未用，占位保布局）
    public var memoryInfoGetVendorId: UnsafeMutableRawPointer?
    /// idx 323: OrtApi::ValueInfo_GetValueProducer（未用，占位保布局）
    public var valueInfo_GetValueProducer: UnsafeMutableRawPointer?
    /// idx 324: OrtApi::ValueInfo_GetValueNumConsumers（未用，占位保布局）
    public var valueInfo_GetValueNumConsumers: UnsafeMutableRawPointer?
    /// idx 325: OrtApi::ValueInfo_GetValueConsumers（未用，占位保布局）
    public var valueInfo_GetValueConsumers: UnsafeMutableRawPointer?
    /// idx 326: OrtApi::ValueInfo_GetInitializerValue（未用，占位保布局）
    public var valueInfo_GetInitializerValue: UnsafeMutableRawPointer?
    /// idx 327: OrtApi::ValueInfo_GetExternalInitializerInfo（未用，占位保布局）
    public var valueInfo_GetExternalInitializerInfo: UnsafeMutableRawPointer?
    /// idx 328: OrtApi::ValueInfo_IsRequiredGraphInput（未用，占位保布局）
    public var valueInfo_IsRequiredGraphInput: UnsafeMutableRawPointer?
    /// idx 329: OrtApi::ValueInfo_IsOptionalGraphInput（未用，占位保布局）
    public var valueInfo_IsOptionalGraphInput: UnsafeMutableRawPointer?
    /// idx 330: OrtApi::ValueInfo_IsGraphOutput（未用，占位保布局）
    public var valueInfo_IsGraphOutput: UnsafeMutableRawPointer?
    /// idx 331: OrtApi::ValueInfo_IsConstantInitializer（未用，占位保布局）
    public var valueInfo_IsConstantInitializer: UnsafeMutableRawPointer?
    /// idx 332: OrtApi::ValueInfo_IsFromOuterScope（未用，占位保布局）
    public var valueInfo_IsFromOuterScope: UnsafeMutableRawPointer?
    /// idx 333: OrtApi::Graph_GetName（未用，占位保布局）
    public var graph_GetName: UnsafeMutableRawPointer?
    /// idx 334: OrtApi::Graph_GetModelPath（未用，占位保布局）
    public var graph_GetModelPath: UnsafeMutableRawPointer?
    /// idx 335: OrtApi::Graph_GetOnnxIRVersion（未用，占位保布局）
    public var graph_GetOnnxIRVersion: UnsafeMutableRawPointer?
    /// idx 336: OrtApi::Graph_GetNumOperatorSets（未用，占位保布局）
    public var graph_GetNumOperatorSets: UnsafeMutableRawPointer?
    /// idx 337: OrtApi::Graph_GetOperatorSets（未用，占位保布局）
    public var graph_GetOperatorSets: UnsafeMutableRawPointer?
    /// idx 338: OrtApi::Graph_GetNumInputs（未用，占位保布局）
    public var graph_GetNumInputs: UnsafeMutableRawPointer?
    /// idx 339: OrtApi::Graph_GetInputs（未用，占位保布局）
    public var graph_GetInputs: UnsafeMutableRawPointer?
    /// idx 340: OrtApi::Graph_GetNumOutputs（未用，占位保布局）
    public var graph_GetNumOutputs: UnsafeMutableRawPointer?
    /// idx 341: OrtApi::Graph_GetOutputs（未用，占位保布局）
    public var graph_GetOutputs: UnsafeMutableRawPointer?
    /// idx 342: OrtApi::Graph_GetNumInitializers（未用，占位保布局）
    public var graph_GetNumInitializers: UnsafeMutableRawPointer?
    /// idx 343: OrtApi::Graph_GetInitializers（未用，占位保布局）
    public var graph_GetInitializers: UnsafeMutableRawPointer?
    /// idx 344: OrtApi::Graph_GetNumNodes（未用，占位保布局）
    public var graph_GetNumNodes: UnsafeMutableRawPointer?
    /// idx 345: OrtApi::Graph_GetNodes（未用，占位保布局）
    public var graph_GetNodes: UnsafeMutableRawPointer?
    /// idx 346: OrtApi::Graph_GetParentNode（未用，占位保布局）
    public var graph_GetParentNode: UnsafeMutableRawPointer?
    /// idx 347: OrtApi::Graph_GetGraphView（未用，占位保布局）
    public var graph_GetGraphView: UnsafeMutableRawPointer?
    /// idx 348: OrtApi::Node_GetId（未用，占位保布局）
    public var node_GetId: UnsafeMutableRawPointer?
    /// idx 349: OrtApi::Node_GetName（未用，占位保布局）
    public var node_GetName: UnsafeMutableRawPointer?
    /// idx 350: OrtApi::Node_GetOperatorType（未用，占位保布局）
    public var node_GetOperatorType: UnsafeMutableRawPointer?
    /// idx 351: OrtApi::Node_GetDomain（未用，占位保布局）
    public var node_GetDomain: UnsafeMutableRawPointer?
    /// idx 352: OrtApi::Node_GetSinceVersion（未用，占位保布局）
    public var node_GetSinceVersion: UnsafeMutableRawPointer?
    /// idx 353: OrtApi::Node_GetNumInputs（未用，占位保布局）
    public var node_GetNumInputs: UnsafeMutableRawPointer?
    /// idx 354: OrtApi::Node_GetInputs（未用，占位保布局）
    public var node_GetInputs: UnsafeMutableRawPointer?
    /// idx 355: OrtApi::Node_GetNumOutputs（未用，占位保布局）
    public var node_GetNumOutputs: UnsafeMutableRawPointer?
    /// idx 356: OrtApi::Node_GetOutputs（未用，占位保布局）
    public var node_GetOutputs: UnsafeMutableRawPointer?
    /// idx 357: OrtApi::Node_GetNumImplicitInputs（未用，占位保布局）
    public var node_GetNumImplicitInputs: UnsafeMutableRawPointer?
    /// idx 358: OrtApi::Node_GetImplicitInputs（未用，占位保布局）
    public var node_GetImplicitInputs: UnsafeMutableRawPointer?
    /// idx 359: OrtApi::Node_GetNumAttributes（未用，占位保布局）
    public var node_GetNumAttributes: UnsafeMutableRawPointer?
    /// idx 360: OrtApi::Node_GetAttributes（未用，占位保布局）
    public var node_GetAttributes: UnsafeMutableRawPointer?
    /// idx 361: OrtApi::Node_GetAttributeByName（未用，占位保布局）
    public var node_GetAttributeByName: UnsafeMutableRawPointer?
    /// idx 362: OrtApi::OpAttr_GetTensorAttributeAsOrtValue（未用，占位保布局）
    public var opAttr_GetTensorAttributeAsOrtValue: UnsafeMutableRawPointer?
    /// idx 363: OrtApi::OpAttr_GetType（未用，占位保布局）
    public var opAttr_GetType: UnsafeMutableRawPointer?
    /// idx 364: OrtApi::OpAttr_GetName（未用，占位保布局）
    public var opAttr_GetName: UnsafeMutableRawPointer?
    /// idx 365: OrtApi::Node_GetNumSubgraphs（未用，占位保布局）
    public var node_GetNumSubgraphs: UnsafeMutableRawPointer?
    /// idx 366: OrtApi::Node_GetSubgraphs（未用，占位保布局）
    public var node_GetSubgraphs: UnsafeMutableRawPointer?
    /// idx 367: OrtApi::Node_GetGraph（未用，占位保布局）
    public var node_GetGraph: UnsafeMutableRawPointer?
    /// idx 368: OrtApi::Node_GetEpName（未用，占位保布局）
    public var node_GetEpName: UnsafeMutableRawPointer?
    /// idx 369: OrtApi::ReleaseExternalInitializerInfo（未用，占位保布局）
    public var releaseExternalInitializerInfo: UnsafeMutableRawPointer?
    /// idx 370: OrtApi::ExternalInitializerInfo_GetFilePath（未用，占位保布局）
    public var externalInitializerInfo_GetFilePath: UnsafeMutableRawPointer?
    /// idx 371: OrtApi::ExternalInitializerInfo_GetFileOffset（未用，占位保布局）
    public var externalInitializerInfo_GetFileOffset: UnsafeMutableRawPointer?
    /// idx 372: OrtApi::ExternalInitializerInfo_GetByteSize（未用，占位保布局）
    public var externalInitializerInfo_GetByteSize: UnsafeMutableRawPointer?
    /// idx 373: OrtApi::GetRunConfigEntry（未用，占位保布局）
    public var getRunConfigEntry: UnsafeMutableRawPointer?
    /// idx 374: OrtApi::EpDevice_MemoryInfo（未用，占位保布局）
    public var epDevice_MemoryInfo: UnsafeMutableRawPointer?
    /// idx 375: OrtApi::CreateSharedAllocator（未用，占位保布局）
    public var createSharedAllocator: UnsafeMutableRawPointer?
    /// idx 376: OrtApi::GetSharedAllocator（未用，占位保布局）
    public var getSharedAllocator: UnsafeMutableRawPointer?
    /// idx 377: OrtApi::ReleaseSharedAllocator（未用，占位保布局）
    public var releaseSharedAllocator: UnsafeMutableRawPointer?
    /// idx 378: OrtApi::GetTensorData（未用，占位保布局）
    public var getTensorData: UnsafeMutableRawPointer?
    /// idx 379: OrtApi::GetSessionOptionsConfigEntries（未用，占位保布局）
    public var getSessionOptionsConfigEntries: UnsafeMutableRawPointer?
    /// idx 380: OrtApi::SessionGetMemoryInfoForInputs（未用，占位保布局）
    public var sessionGetMemoryInfoForInputs: UnsafeMutableRawPointer?
    /// idx 381: OrtApi::SessionGetMemoryInfoForOutputs（未用，占位保布局）
    public var sessionGetMemoryInfoForOutputs: UnsafeMutableRawPointer?
    /// idx 382: OrtApi::SessionGetEpDeviceForInputs（未用，占位保布局）
    public var sessionGetEpDeviceForInputs: UnsafeMutableRawPointer?
    /// idx 383: OrtApi::CreateSyncStreamForEpDevice（未用，占位保布局）
    public var createSyncStreamForEpDevice: UnsafeMutableRawPointer?
    /// idx 384: OrtApi::SyncStream_GetHandle（未用，占位保布局）
    public var syncStream_GetHandle: UnsafeMutableRawPointer?
    /// idx 385: OrtApi::ReleaseSyncStream（未用，占位保布局）
    public var releaseSyncStream: UnsafeMutableRawPointer?
    /// idx 386: OrtApi::CopyTensors（未用，占位保布局）
    public var copyTensors: UnsafeMutableRawPointer?
    /// idx 387: OrtApi::Graph_GetModelMetadata（未用，占位保布局）
    public var graph_GetModelMetadata: UnsafeMutableRawPointer?
    /// idx 388: OrtApi::GetModelCompatibilityForEpDevices（未用，占位保布局）
    public var getModelCompatibilityForEpDevices: UnsafeMutableRawPointer?
    /// idx 389: OrtApi::CreateExternalInitializerInfo（未用，占位保布局）
    public var createExternalInitializerInfo: UnsafeMutableRawPointer?
    /// idx 390: OrtApi::TensorTypeAndShape_HasShape（未用，占位保布局）
    public var tensorTypeAndShape_HasShape: UnsafeMutableRawPointer?
    /// idx 391: OrtApi::KernelInfo_GetConfigEntries（未用，占位保布局）
    public var kernelInfo_GetConfigEntries: UnsafeMutableRawPointer?
    /// idx 392: OrtApi::KernelInfo_GetOperatorDomain（未用，占位保布局）
    public var kernelInfo_GetOperatorDomain: UnsafeMutableRawPointer?
    /// idx 393: OrtApi::KernelInfo_GetOperatorType（未用，占位保布局）
    public var kernelInfo_GetOperatorType: UnsafeMutableRawPointer?
    /// idx 394: OrtApi::KernelInfo_GetOperatorSinceVersion（未用，占位保布局）
    public var kernelInfo_GetOperatorSinceVersion: UnsafeMutableRawPointer?
    /// idx 395: OrtApi::GetInteropApi（未用，占位保布局）
    public var getInteropApi: UnsafeMutableRawPointer?
    /// idx 396: OrtApi::SessionGetEpDeviceForOutputs（未用，占位保布局）
    public var sessionGetEpDeviceForOutputs: UnsafeMutableRawPointer?
    /// idx 397: OrtApi::GetNumHardwareDevices（未用，占位保布局）
    public var getNumHardwareDevices: UnsafeMutableRawPointer?
    /// idx 398: OrtApi::GetHardwareDevices（未用，占位保布局）
    public var getHardwareDevices: UnsafeMutableRawPointer?
    /// idx 399: OrtApi::GetHardwareDeviceEpIncompatibilityDetails（未用，占位保布局）
    public var getHardwareDeviceEpIncompatibilityDetails: UnsafeMutableRawPointer?
    /// idx 400: OrtApi::DeviceEpIncompatibilityDetails_GetReasonsBitmask（未用，占位保布局）
    public var deviceEpIncompatibilityDetails_GetReasonsBitmask: UnsafeMutableRawPointer?
    /// idx 401: OrtApi::DeviceEpIncompatibilityDetails_GetNotes（未用，占位保布局）
    public var deviceEpIncompatibilityDetails_GetNotes: UnsafeMutableRawPointer?
    /// idx 402: OrtApi::DeviceEpIncompatibilityDetails_GetErrorCode（未用，占位保布局）
    public var deviceEpIncompatibilityDetails_GetErrorCode: UnsafeMutableRawPointer?
    /// idx 403: OrtApi::ReleaseDeviceEpIncompatibilityDetails（未用，占位保布局）
    public var releaseDeviceEpIncompatibilityDetails: UnsafeMutableRawPointer?
    /// idx 404: OrtApi::GetCompatibilityInfoFromModel（未用，占位保布局）
    public var getCompatibilityInfoFromModel: UnsafeMutableRawPointer?
    /// idx 405: OrtApi::GetCompatibilityInfoFromModelBytes（未用，占位保布局）
    public var getCompatibilityInfoFromModelBytes: UnsafeMutableRawPointer?
    /// idx 406: OrtApi::CreateEnvWithOptions（未用，占位保布局）
    public var createEnvWithOptions: UnsafeMutableRawPointer?
    /// idx 407: OrtApi::Session_GetEpGraphAssignmentInfo（未用，占位保布局）
    public var session_GetEpGraphAssignmentInfo: UnsafeMutableRawPointer?
    /// idx 408: OrtApi::EpAssignedSubgraph_GetEpName（未用，占位保布局）
    public var epAssignedSubgraph_GetEpName: UnsafeMutableRawPointer?
    /// idx 409: OrtApi::EpAssignedSubgraph_GetNodes（未用，占位保布局）
    public var epAssignedSubgraph_GetNodes: UnsafeMutableRawPointer?
    /// idx 410: OrtApi::EpAssignedNode_GetName（未用，占位保布局）
    public var epAssignedNode_GetName: UnsafeMutableRawPointer?
    /// idx 411: OrtApi::EpAssignedNode_GetDomain（未用，占位保布局）
    public var epAssignedNode_GetDomain: UnsafeMutableRawPointer?
    /// idx 412: OrtApi::EpAssignedNode_GetOperatorType（未用，占位保布局）
    public var epAssignedNode_GetOperatorType: UnsafeMutableRawPointer?
    /// idx 413: OrtApi::RunOptionsSetSyncStream（未用，占位保布局）
    public var runOptionsSetSyncStream: UnsafeMutableRawPointer?
    /// idx 414: OrtApi::GetTensorElementTypeAndShapeDataReference（未用，占位保布局）
    public var getTensorElementTypeAndShapeDataReference: UnsafeMutableRawPointer?
    /// idx 415: OrtApi::RunOptionsEnableProfiling（未用，占位保布局）
    public var runOptionsEnableProfiling: UnsafeMutableRawPointer?
    /// idx 416: OrtApi::RunOptionsDisableProfiling（未用，占位保布局）
    public var runOptionsDisableProfiling: UnsafeMutableRawPointer?
    /// idx 417: OrtApi::KernelInfoGetAttributeArray_string（未用，占位保布局）
    public var kernelInfoGetAttributeArray_string: UnsafeMutableRawPointer?
    /// idx 418: OrtApi::SetPerSessionThreadPoolCallbacks（未用，占位保布局）
    public var setPerSessionThreadPoolCallbacks: UnsafeMutableRawPointer?
    /// idx 419: OrtApi::GetMemPatternEnabled（未用，占位保布局）
    public var getMemPatternEnabled: UnsafeMutableRawPointer?
    /// idx 420: OrtApi::GetSessionExecutionMode（未用，占位保布局）
    public var getSessionExecutionMode: UnsafeMutableRawPointer?
    /// idx 421: OrtApi::SessionReleaseCapturedGraph（未用，占位保布局）
    public var sessionReleaseCapturedGraph: UnsafeMutableRawPointer?
    /// idx 422: OrtApi::GetExperimentalFunction（未用，占位保布局）
    public var getExperimentalFunction: UnsafeMutableRawPointer?
    /// idx 423: OrtApi::KernelContext_GetSyncStream（未用，占位保布局）
    public var kernelContext_GetSyncStream: UnsafeMutableRawPointer?
    /// idx 424: OrtApi::SessionOptionsSetWeightlessSourceModelBuffer（未用，占位保布局）
    public var sessionOptionsSetWeightlessSourceModelBuffer: UnsafeMutableRawPointer?
}
